language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
before_install: ./travis.sh
install: pip install .
cache:
  directories:
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION*/lib/python*/site-packages
script: python setup.py test
notifications:
  email: false
