language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
before_install: ./travis.sh
install: pip install .
cache:
  directories:
    - $HOME/.pip-cache
script: python setup.py test
notifications:
  email: false
