language: python
sudo: false
notifications:
  email: false

python:
  - "3.4"
  - "3.5"

env:
  - GAMS=24.4
    GAMS_URL=http://d37drm4t2jghv5.cloudfront.net/distributions/24.4.3/linux/linux_x64_64_sfx.exe

before_install:
  - mkdir -p $HOME/.cache/gams/$GAMS
  - wget -N $GAMS_URL -P $HOME/.cache/gams/$GAMS/
  - unzip $HOME/.cache/gams/$GAMS/*.exe
  - ln -s gams* gams
  - cd gams
  - ./gamsinst -a
  - cd -
  - cd gams/apifiles/Python/api
  - python gdxsetup.py install
  - cd -
  - export PATH=$HOME/gams:$PATH

install:
  - pip install -r data/test-requirements.txt
  - python setup.py install

cache:
  pip: true
  directories:
    - $HOME/.cache/gams

script: py.test gdx --cov=gdx

after_success:
  - coveralls
