language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

before_install: ./travis.sh before_install

install: pip install .

cache:
  directories:
    - $HOME/gams
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION*/lib/python*/site-packages

script: ./travis.sh build

notifications:
  email: false
