language: python
sudo: false
notifications:
  email: false

python:
  - 2.7
  - 3.4
  - 3.5

env:
  global:
    - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - GAMS=24.7
    - GAMS_URL=https://d37drm4t2jghv5.cloudfront.net/distributions/24.7.3/linux/linux_x64_64_sfx.exe
    - GAMS_API=api

before_install:
  # Install Miniconda
  - wget -N $MINICONDA_URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Install GAMS
  - wget -N $GAMS_URL -O gams.zip
  - unzip -qu gams.zip -d $HOME
  - ln -s $HOME/gams${GAMS}_linux_x64_64_sfx $HOME/gams
  - export PATH="$HOME/gams:$PATH"
  - cd $HOME/gams
  - gamsinst -a
  - cd -

install:
  # Prepare the Anaconda environment
  - conda env create --file data/test-requirements-$TRAVIS_PYTHON_VERSION.yml
  - source activate test_env
  # Install the GAMS GDX Python API into the environment
  - cd $HOME/gams/apifiles/Python/$GAMS_API
  - python gdxsetup.py install
  - cd -
  # Install PyGDX
  - python setup.py install

script:
    - py.test gdx --cov=gdx --cov-report term-missing

after_success:
  - coveralls
